### ISSUE TITLE
Accessibility Insights

### ISSUE THREAD

**Issue by tpkahlon** [brunopulis/awesome-a11y#132]
**Proposal**

- Add Accessibility Insights from Microsoft

**Demo**

- [Repository](https://github.com/microsoft/accessibility-insights-web)
- [Reference](https://accessibilityinsights.io/)

**Checkpoints**

- Confirm if this feature is already part of this living documentation
- If no, get a go ahead to create a Merge request

**Comment by brunopulis** [comment]
Hey @tpkahlon it's a great idea, but I think the Accessibility Insights was added before. I will check in the repository, if wasn't added you can add. =)
