### ISSUE TITLE
Consider adding Checka11y.css?

### ISSUE THREAD

**Issue by jackdomleo7** [brunopulis/awesome-a11y#134]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I feel Checka11y.css has become a popular project with people learn accessibility and people looking for a cool project that highlights accessibility in a different way. It's also extremely popular during Hacktoberfest.

**Describe alternatives you've considered**
N/A

**Additional context**
Links:
- https://checka11y.jackdomleo.dev
- https://github.com/jackdomleo7/Checka11y.css
- https://github.com/jackdomleo7/Checka11y.css-browser-extension

**Comment by brunopulis** [comment]
Hey, @jackdomleo7 I didn't know about the project. I will include it in the Awesome. Thanks for sharing. =)

**Comment by brunopulis** [comment]
Added 🚀
