### ISSUE TITLE
Cursos da W3C não disponíveis

### ISSUE THREAD

**Issue by gustavo-marcialis** [brunopulis/awesome-a11y#175]
Os cursos "Padrões HTML5, CSS3 e Acessibilidade" e "Web Semântica" do W3C não estão mais disponíveis, da página não encontrada.

**Comment by brunopulis** [comment]
> Os cursos "Padrões HTML5, CSS3 e Acessibilidade" e "Web Semântica" do W3C não estão mais disponíveis, da página não encontrada.

Obrigado por avisar @gustavo-marcialis irei remover.

**Comment by gustavo-marcialis** [comment]
Seria interessante procurar algum outro grátis pra substituir...

**Comment by brunopulis** [comment]
@gustavo-marcialis seria bacana mesmo, caso encontre algum pode abrir um PR :)

**Comment by brunopulis** [comment]
Atualizado #177
