### ISSUE TITLE
Why legends ?

### ISSUE THREAD

**Issue by audreymaniez** [brunopulis/awesome-a11y#56]
Hello, 

Nice initiative !  thank you for your work.

But why do you use legend for level description ? 

The legend is hard to memorize, and, for a screen reader user, the content of the icon's alt attribute is not really helpful (it describes the icon). I search through the code, but it seems i can't find alternative information about the level next to the icon, but maybe I just didn't see it.

Why don't you just put the text level instead of the icon and remove the legend ?

**Comment by brunopulis** [comment]
Hi @audreymaniez , I'm glad you liked it =)

As for the description with caption was a way I thought to organize the content better but had not attacked that detail you mentioned.

Perhaps, using only textual information is better.
I'm open to suggestions

Thank you again.

**Comment by audreymaniez** [comment]
Nice you did it !!

Thank you :-)
