### ISSUE TITLE
404 on google's accessibility guide

### ISSUE THREAD

**Issue by skorasaurus** [brunopulis/awesome-a11y#98]
In [Guides](https://github.com/brunopulis/awesome-a11y/blob/master/topics/guides.md), Link to google's intro to web accessibility is a 404; 

there's now https://developers.google.com/web/fundamentals/accessibility/ 
or https://www.udacity.com/course/web-accessibility--ud891# (developed in partnership with google) and not sure which you prefer to replace the previous link with.

**Comment by brunopulis** [comment]
@skorasaurus fixed, thank you so much :)
