### ISSUE TITLE
People to follow resource

### ISSUE THREAD

**Issue by joe-watkins** [brunopulis/awesome-a11y#99]
Hello, wanted to alert you of a project I have rolling that lots of folks have contributed to you could either point to or steal from! :)

https://github.com/joe-watkins/top-people-to-follow-in-web-accessibility

**Comment by brunopulis** [comment]
Hello @joe-watkins , first of all I would like to thank you for your contact, but I did not quite understand it. I'm sorry I'm learning English and some things I still do not understand very well.

Your indication would be to point to your repository these references or could I get information from it?

**Comment by joe-watkins** [comment]
Hello @brunopulis Yes, you understood correctly. Feel free to reference my list/project or just use it to build yours up! Take care :)

**Comment by brunopulis** [comment]
@joe-watkins I thank you for the advice I will reference your list in the repository. Thank you very much.
